### ISSUE TITLE
Dependency Problems

### ISSUE THREAD

**Issue by chymian** [Drlordbasil/AURORA#7]
from what @Drlordbasil wrote on groq's discord, I was eager to test your app.

1. I tried to install on dokploy with herokuish buildpacks and it failed, "module flask is missing", even so it was installed.

2. I tried local in py-env,:
```
ModuleNotFoundError: No module named 'flask_session'
```

and 
```
pip install flask_session
$ python   ./main.py                                                                                                                   
2024-07-09 15:53:41.654426: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-09 15:53:41.656708: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-09 15:53:41.665506: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-09 15:53:41.683605: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-09 15:53:41.683650: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-09 15:53:41.694495: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-09 15:53:42.361514: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT                                                                                                                                                  
Traceback (most recent call last):
  File "/home/paia/AURORA/./main.py", line 7, in <module>
    from listen_lobe import AuroraRecorder
  File "/home/paia/AURORA/listen_lobe.py", line 2, in <module>
    import sounddevice as sd                                  
  File "/home/paia/AURORA/.venv/lib/python3.12/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found
```

Debian 12, 
Python 3.12.2

do you plan to make docker-images available?

**Comment by Drlordbasil** [comment]
I definitely plan on that and releasing a demo, I've been working mainly on a model to replace groq and ollama for all things that I'm creating from scratch, but I'm just having issues trying to launch this on a demo site tbh because I've never done that haha. 😅 

Either way, I'll release a docker version soon at least. 

I kept failing due to limits and Flask limitations but I may have to redo the app portion fully for the demo. 


Let me review your problem more and I'll get back to you to see if I can't help you at least locally install!

**Comment by Drlordbasil** [comment]
I actually think the aurora recorder may be the problem, for it may just work on my Windows setup, btw. 😳  so i can comment some code out and make a version that doesn't use the voice for now while I work on an all-around solution for all operating systems. 


Either way I'll get the docker image setup hopefully by tonight.

**Comment by Drlordbasil** [comment]
fixed with docker I believe.
